name: pykerberos CI
on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
        - python: 2.7
        - python: 3.6
        - python: 3.7
        - python: 3.8
        - python: 3.9
        - python: '3.10'
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: test build/install
      run: |
        sudo apt-get update -qq
        sudo apt-get install libkrb5-dev

        python -V
        python -m pip install .
